// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABm7PhP-wbyYUj8jpUy5e0wniyeYtpNug',
    appId: '1:127594592035:web:69df6481ebed759da73e96',
    messagingSenderId: '127594592035',
    projectId: 'gadcotopaxi-4375a',
    authDomain: 'gadcotopaxi-4375a.firebaseapp.com',
    storageBucket: 'gadcotopaxi-4375a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARwlYdk2aVuXv3jYvLodUZUBCsiLXNxD8',
    appId: '1:127594592035:android:c328564cf47594e6a73e96',
    messagingSenderId: '127594592035',
    projectId: 'gadcotopaxi-4375a',
    storageBucket: 'gadcotopaxi-4375a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0C2HmHCjgVSNlSfcP8BtW5FYd1CGFidI',
    appId: '1:127594592035:ios:4c57ca574bf16cc8a73e96',
    messagingSenderId: '127594592035',
    projectId: 'gadcotopaxi-4375a',
    storageBucket: 'gadcotopaxi-4375a.appspot.com',
    iosBundleId: 'com.example.gad',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABm7PhP-wbyYUj8jpUy5e0wniyeYtpNug',
    appId: '1:127594592035:web:75a326953471c101a73e96',
    messagingSenderId: '127594592035',
    projectId: 'gadcotopaxi-4375a',
    authDomain: 'gadcotopaxi-4375a.firebaseapp.com',
    storageBucket: 'gadcotopaxi-4375a.appspot.com',
  );
}
